name: Update Website

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v2
      - name: Build and Update Website
        run: |
          # Always install packages before building
          bundle install && yarn install

          # Fix Weird Permission Issue
          sudo chmod -R 777 ../*

          # Build for production
          bin/bridgetown deploy
          
          # Clean Up
          sudo rm -R /usr/share/nginx/w/discordunspy/*

          # Copy to NGINX directory
          sudo mv ./output/ ./discordunspy/
          sudo rm -R /usr/share/nginx/w/discordunspy/
          sudo cp -R ./discordunspy/ /usr/share/nginx/w/
